### PR TITLE
Suggestion for where to put the acknowledgements

### PR DESCRIPTION
**Pull request by kallewesterling**
Here's where I'd suggest we would put acknowledgements such as these (I haven't really seen any others yet in the other repos but maybe I just haven't looked for them!)

### CODE REVIEW

**Comment by smythp** [comment]
Let's not mess with the standard format of the title page because that page needs to be manipulated programmatically to produce other outputs. Otherwise I think it's fine at the beginning or the end, or even at the end of the workshop description, though I think it's a bit messy there.

**Comment by kallewesterling** [comment]
You mean that there's a script that pulls in the acknowledgements programmatically somewhere (GitBook)? Wouldn't that still work with an added line that the script could just filter out.. (i.e. ``if the beginning of the string == "Acknowledgments:" then go ahead and skip``?)

**Comment by smythp** [comment]
Yes, but edge cases are bad and require maintenance and I don't think it's worth it.

**Comment by kallewesterling** [comment]
OK, let's put it at the end of the workshop description and see what it looks like!

**Pull request closed without merging**
